### ISSUE TITLE
accuraterip-checksum.c:121:44: warning: division by zero [-Wdiv-by-zero]

### ISSUE THREAD

**Issue by MerlijnWajer** [leo-bogert/accuraterip-checksum#2]
Compiling with GCC, I get this:

$ gcc -std=gnu99  -lsndfile accuraterip-checksum.c -o accuraterip-checksum
accuraterip-checksum.c: In function ‘compute_v2_checksum’:
accuraterip-checksum.c:121:44: warning: division by zero [-Wdiv-by-zero]

The problem is that you define "__int64" as long. That is not correct, you should use the proper type for this. You should include stdint.h and use uint64_t

**Comment by leo-bogert** [comment]
Fixed in the most recent version on branch master.
